export const darkTheme = {
  body: "#141B2D",
  button: "#F6F9F6",
  buttonTitle: "#141B2D",
  title: "#FFFFFF",
  shadow:'#1C1C1C',
  footerBackground: "radial-gradient(circle at top, #0b1020, #060914)",
  applicationLogo:
    "brightness(0) saturate(100%) invert(100%) sepia(100%) saturate(100%) hue-rotate(198deg) brightness(100%) contrast(100%)",
  headerBody: "#182034",
  borders: "#253344",
  heroPageBackground: " #000000",
  freePlanContainer: "#1F2940",
  testreportcontainer: "#1F1F21",
  freePlanTimer: "transparent",
  freePlanTimerBorder: "#f45a51",
  subtitle: "#9B9B9D",
  icon: "#b6b6b6",
  sidebarMenuIcons: "#FFFFFF",
  sideMenu: "#1F2940",
  sliderSelectedText: "#EFEFEF",
  siderMenuSelectedBackground: "#0D162B",
  siderMenuHoverEffect: "#EFEFEF",
  sideMenuIconSelectedColor:
    "invert(100%) sepia(100%) saturate(0%) hue-rotate(0deg) brightness(100%) contrast(100%)",
  sideMenuTitle: "#9B9B9D",
  card: "#182034",
  cardBorder: "#253344",
  cardHeader: "#1F1F21",
  sliderText: "#7782A1",
  createNewApplicationCard: "#182034",
  text: "#9B9B9D",
  buttonTypeDashedBackground: "#1F2940",
  buttonTypeDashedText: "#EFEFEF",
  buttonTypeDashedBorder: "#1F2940",
  darkModeButtonBackground: "#0D162B",
  modalBackgroundColor: "#1F1F21",
  scrollBarTrackBackground: "#0D162B",
  scrollBarThumbBackground: "#e0e0e0",
  scrollBarThumbHoverBackground: "#ffffff",

  tenantheader: "#0D162B",
  browseExtensionIcon:
    "brightness(0) saturate(100%) invert(100%) sepia(0%) saturate(7500%) hue-rotate(100deg) brightness(105%) contrast(101%)",
  onBoardingBackgroundImage: "/images/onboarding-dark-mode-background.png",
  signInBackgroundImage: "/images/darkThemeImages/signInDarkMode.png",

  onBoardingCardsBoxShadow: " -2px 0px 33.5px 0px #171717",
  signInPageBackgroundColor: "#1F1F21",
  inputPlaceHolderColor: "#606060",
  dashboardWidgetCardsHeader: "#0D162B",
  createNewApplicationCardIcon:
    "/images/darkThemeImages/createNewApplicationDarkMode.svg",
  tableHeader: "#141B2D",
  tableBody: "#1F2940",
  reportModalHelpContainer: "#0D162B",
  inputBoxBackground: "#0D162B",
  profileIcon: "/images/darkThemeImages/profileIconDarkMode.svg",
  securitySettingsIcon: "/images/darkThemeImages/password.svg",
  authenticationIcon: "/images/darkThemeImages/authentication.svg",
  signOutIcon: "/images/darkThemeImages/signout.svg",
  planAndBillingIcon: "/images/darkThemeImages/planAndBillingIcon.svg",
  inviteUsersIcon: "/images/darkThemeImages/inviteUsersIcon.svg",
  refferIcon: "/images/darkThemeImages/refferIcon.svg",
  noReportFound: "/images/icons/empty-report.svg",
  tableHeaderColor: "#fff",
  dashboardWidgetsTableBorders: "#253344",
  dashboardWidgetsTableCells: "#fff",
  platformDistributionWidgetsTitle: "#fff",
  campaignOverviewMiniCardsBg: "#1F2940",
  googleCardGradient: "linear-gradient(180deg,#0f2a3d -59.51%,#0d3b2f 100%)",
  facebookMiniCardGradient: "linear-gradient(180deg, #2b3f59 0%, #1e2d47 100%)",
  instaMiniCardGradient: "linear-gradient(180deg, #4a1f33 0%, #2a0f26 100%)",
  rainbowText: "#FFFFFF",
  buttonHoverText: "#141B2D",
  gradientText: "linear-gradient(45deg, #e8eaf0,#4c80e1, #ba5fe8)",
  appleHeadingText: "#1D1D1F",
  appleText: "#86868B",
  appleGrayText: "#F5F5F7",
  appleBackground: "#F5F5F7",
  segmentBackground:
    "radial-gradient( circle at 70% 60%, #ffffff 0%, #f2f2f2 35%, #e6e6e6 65%, #d9d9d9 100% ), linear-gradient( 135deg, #ffffff 0%, #f5f5f5 50%, #ebebeb 100% );",
};

export const lightTheme = {
  segmentBackground:
    "linear-gradient( 135deg, #0b0b0b 0%, #111111 35%, #1a1a1a 55%, #2a2a2a 75%, #3a3a3a 100% )",

  appleBackground: "#F5F5F7",
  appleGrayText: "#F5F5F7",
  appleText: "#86868B",
  appleHeadingText: "#1D1D1F",
  rainbowText:
    "linear-gradient(90deg, #ff0000, #00ff00, #0000ff, #4b0082, #8f00ff 100%)",
  body: "#F6F9F6",
  heroPageBackground:
    "linear-gradient( 135deg, #f8fafc 0%, #e8f1ff 35%, #e9e4ff 65%, #f3e8ff 100%)",
  button: "#141B2D",
  footerBackground: "radial-gradient(circle at top, #0b1020, #060914)",
  buttonTitle: "#F6F9F6",
  buttonHoverText: "#141B2D",
  headerBody: "#FFFFFF",
  borders: "#EAEBEE",
  freePlanContainer: "#FFFFFF",
  testreportcontainer: "#FFFFFF",
  freePlanTimer: "#fff2f4",
  freePlanTimerBorder: "#fff2f4",
  title: "#1C1C1C",
  shadow:'#1C1C1C',
  icon: "#1c1c1c",
  subtitle: "#7782A1",
  sideMenu: "#FFFFFF",
  sidebarMenuIcons: "#000000",
  gradientText: "linear-gradient(45deg, #6297fb, #6045d8)",

  siderMenuSelectedBackground: "#F4F4FF",
  siderMenuHoverEffect: "#5550FF",
  sideMenuIconSelectedColor:
    "invert(27%) sepia(82%) saturate(7423%) hue-rotate(228deg) brightness(95%) contrast(101%)",
  sideMenuTitle: "#9B9B9D",
  sliderSelectedText: "#5550FF",
  sliderText: "#5550FF",
  card: "#FFFFFF",
  cardBorder: "#EAEBEE",
  cardHeader: "#FAFAFC",
  createNewApplicationCard: "#5550FF",
  text: "#4A4A4A",

  buttonTypeDashedBackground: "#FFFFFF",
  buttonTypeDashedBorder: "#EAEBEE",

  darkModeButtonBackground: "#FAFAFC",
  modalBackgroundColor: "#FFFFFF",

  scrollBarTrackBackground: "#fafafc",
  scrollBarThumbBackground: "#d2d5da",
  scrollBarThumbHoverBackground: "#6d7280",
  tenantheader: "#FFFFFF",
  browseExtensionIcon:
    "brightness(0) saturate(100%) invert(0%) sepia(0%) saturate(7500%) hue-rotate(100deg) brightness(105%) contrast(101%)",
  signInBackgroundImage: "/images/signIn.png",
  onBoardingBackgroundImage: "/images/onboarding-background-image.png",
  onBoardingCardsBoxShadow: "-2px 0px 33.5px 0px #D9E0F4",
  signInPageBackgroundColor: "#FFFFFF",
  dashboardWidgetCardsHeader: "#001529",
  inputPlaceHolderColor: "#CDD3E8",
  createNewApplicationCardIcon: "/images/startFromScratch.svg",
  tableHeader: "#FAFAFC",
  tableBody: "#FFFFFF",
  reportModalHelpContainer: "#eee7e6",
  inputBoxBackground: "#FFFFFF",
  profileIcon: "/images/icons/profile.png",
  securitySettingsIcon: "/images/icons/password.png",
  authenticationIcon: "/images/icons/authentication.png",
  signOutIcon: "/images/icons/signout.png",
  planAndBillingIcon: "/images/icons/plan.png",
  inviteUsersIcon: "/images/icons/inviteUsersIcon.png",
  refferIcon: "/images/icons/earn.png",
  noReportFound: "/images/empty-report.png",
  tableHeaderColor: "#64748B",
  dashboardWidgetsTableBorders: "#EAECF0",
  dashboardWidgetsTableCells: "#101828",
  platformDistributionWidgetsTitle: "#334763",
  campaignOverviewMiniCardsBg: "#f9fbfc",
  googleCardGradient: "linear-gradient(180deg, #d4f0ff -59.51%, #d0ffe6 100%)",
  facebookMiniCardGradient:
    "linear-gradient(180deg, #cce8ff -59.51%, #b3dcff 100%)",
  instaMiniCardGradient: "linear-gradient(180deg, #ffd6ec 0%, #f5c2f0 100%)",
};

export type LightThemeType = typeof lightTheme;
export type DarkThemeType = typeof darkTheme;

export type Theme = Partial<LightThemeType & DarkThemeType>;
